export const useCollectionStore = defineStore("collection", {
	state: () => ({
		titles: [
			{
				title: "Collection",
			},
			{
				title: "Volume",
			},
			{
				title: "24h %",
			},
			{
				title: "Floor Price",
			},
			{
				title: "Owners",
			},
			{
				title: "Items",
			},
		],

		items: [
			{
				img: "/img/mini/1.png",
				name: "Alex Ca.",
				nickname: "By Alex",
				volume: "8,456",
				sale: "+ 27.78%",
				price: "3,5",
				owners: "2.2K",
				items: "500",
			},
			{
				img: "/img/mini/2.jpeg",
				name: "Alex Ca.",
				nickname: "By Alex",
				volume: "4,780",
				sale: "- 27.78%",
				price: "7,9",
				owners: "3.4K",
				items: "900",
			},
			{
				img: "/img/mini/1.png",
				name: "Alex Ca.",
				nickname: "By Alex",
				volume: "8,456",
				sale: "+ 27.78%",
				price: "3,5",
				owners: "2.2K",
				items: "500",
			},
			{
				img: "/img/mini/2.jpeg",
				name: "Alex Ca.",
				nickname: "By Alex",
				volume: "4,780",
				sale: "- 27.78%",
				price: "7,9",
				owners: "3.4K",
				items: "900",
			},
			{
				img: "/img/mini/1.png",
				name: "Alex Ca.",
				nickname: "By Alex",
				volume: "8,456",
				sale: "- 27.78%",
				price: "3,5",
				owners: "2.2K",
				items: "500",
			},
			{
				img: "/img/mini/2.jpeg",
				name: "Alex Ca.",
				nickname: "By Alex",
				volume: "4,780",
				sale: "+ 27.78%",
				price: "7,9",
				owners: "3.4K",
				items: "900",
			},
			{
				img: "/img/mini/1.png",
				name: "Alex Ca.",
				nickname: "By Alex",
				volume: "8,456",
				sale: "+ 27.78%",
				price: "3,5",
				owners: "2.2K",
				items: "500",
			},
			{
				img: "/img/mini/2.jpeg",
				name: "Alex Ca.",
				nickname: "By Alex",
				volume: "4,780",
				sale: "+ 27.78%",
				price: "7,9",
				owners: "3.4K",
				items: "900",
			},
		],
	}),
});
