export const useRecommendStore = defineStore("recommend", {
	state: () => ({
		slides: [
			{
				id: "1",
				timer: "07h 09m 12s",
				img: "/img/nfts/1.png",
				creatorAva: "/img/creators/1.png",
				creatorName: "Perperzon",
				ownerAva: "/img/owners/1.png",
				ownerName: "Videz",
				title: "Sun-Glass",
				description: "A collection of 10,000 utility-enabled PFPs that feature a richly diverse and unique pool of rarity-powered traits. ",
				price: "1.75",
			},
			{
				id: "2",
				timer: "04h 22m 52s",
				img: "/img/nfts/2.png",
				creatorAva: "/img/creators/1.png",
				creatorName: "Perperzon",
				ownerAva: "/img/owners/1.png",
				ownerName: "Videz",
				title: "Sun-Glass",
				description: "A collection of 10,000 utility-enabled PFPs that feature a richly diverse and unique pool of rarity-powered traits. ",
				price: "1.75",
			},
			{
				id: "3",
				timer: "12h 09m 02s",
				img: "/img/nfts/3.png",
				creatorAva: "/img/creators/1.png",
				creatorName: "Perperzon",
				ownerAva: "/img/owners/1.png",
				ownerName: "Videz",
				title: "Sun-Glass",
				description: "A collection of 10,000 utility-enabled PFPs that feature a richly diverse and unique pool of rarity-powered traits. ",
				price: "1.75",
			},
			{
				id: "4",
				timer: "04h 12m 12s",
				img: "/img/nfts/4.png",
				creatorAva: "/img/creators/1.png",
				creatorName: "Perperzon",
				ownerAva: "/img/owners/1.png",
				ownerName: "Videz",
				title: "Sun-Glass",
				description: "A collection of 10,000 utility-enabled PFPs that feature a richly diverse and unique pool of rarity-powered traits. ",
				price: "1.75",
			},
			{
				id: "5",
				timer: "13h 13m 13s",
				img: "/img/nfts/5.png",
				creatorAva: "/img/creators/1.png",
				creatorName: "Perperzon",
				ownerAva: "/img/owners/1.png",
				ownerName: "Videz",
				title: "Sun-Glass",
				description: "A collection of 10,000 utility-enabled PFPs that feature a richly diverse and unique pool of rarity-powered traits. ",
				price: "1.75",
			},
			{
				id: "6",
				timer: "23h 09m 00s",
				img: "/img/nfts/6.png",
				creatorAva: "/img/creators/1.png",
				creatorName: "Perperzon",
				ownerAva: "/img/owners/1.png",
				ownerName: "Videz",
				title: "Sun-Glass",
				description: "A collection of 10,000 utility-enabled PFPs that feature a richly diverse and unique pool of rarity-powered traits. ",
				price: "1.75",
			},
			{
				id: "7",
				timer: "05h 05m 03s",
				img: "/img/nfts/1.png",
				creatorAva: "/img/creators/1.png",
				creatorName: "Perperzon",
				ownerAva: "/img/owners/1.png",
				ownerName: "Videz",
				title: "Sun-Glass",
				description: "A collection of 10,000 utility-enabled PFPs that feature a richly diverse and unique pool of rarity-powered traits. ",
				price: "1.75",
			},
			{
				id: "8",
				timer: "13h 31m 13s",
				img: "/img/nfts/2.png",
				creatorAva: "/img/creators/1.png",
				creatorName: "Perperzon",
				ownerAva: "/img/owners/1.png",
				ownerName: "Videz",
				title: "Sun-Glass",
				description: "A collection of 10,000 utility-enabled PFPs that feature a richly diverse and unique pool of rarity-powered traits. ",
				price: "1.75",
			},
			{
				id: "9",
				timer: "03h 02m 01s",
				img: "/img/nfts/3.png",
				creatorAva: "/img/creators/1.png",
				creatorName: "Perperzon",
				ownerAva: "/img/owners/1.png",
				ownerName: "Videz",
				title: "Sun-Glass",
				description: "A collection of 10,000 utility-enabled PFPs that feature a richly diverse and unique pool of rarity-powered traits. ",
				price: "1.75",
			},
			{
				id: "10",
				timer: "04h 02m 52s",
				img: "/img/nfts/4.png",
				creatorAva: "/img/creators/1.png",
				creatorName: "Perperzon",
				ownerAva: "/img/owners/1.png",
				ownerName: "Videz",
				title: "Sun-Glass",
				description: "A collection of 10,000 utility-enabled PFPs that feature a richly diverse and unique pool of rarity-powered traits. ",
				price: "1.75",
			},
			{
				id: "11",
				timer: "20h 52m 52s",
				img: "/img/nfts/5.png",
				creatorAva: "/img/creators/1.png",
				creatorName: "Perperzon",
				ownerAva: "/img/owners/1.png",
				ownerName: "Videz",
				title: "Sun-Glass",
				description: "A collection of 10,000 utility-enabled PFPs that feature a richly diverse and unique pool of rarity-powered traits. ",
				price: "1.75",
			},
			{
				id: "12",
				timer: "06h 08m 11s",
				img: "/img/nfts/6.png",
				creatorAva: "/img/creators/1.png",
				creatorName: "Perperzon",
				ownerAva: "/img/owners/1.png",
				ownerName: "Videz",
				title: "Sun-Glass",
				description: "A collection of 10,000 utility-enabled PFPs that feature a richly diverse and unique pool of rarity-powered traits. ",
				price: "1.75",
			},
		],

		sales: [
			{
				img: "/img/mini/1.png",
				count: 1,
				name: "Alex Ca.",
				nickname: "Alexy",
				cost: "8,456",
				sale: "+23,00%",
			},
			{
				img: "/img/mini/2.jpeg",
				count: 2,
				name: "Juliya S.",
				nickname: "JuliyaS",
				cost: "5,327",
				sale: "-32,01%",
			},
		],
	}),
});
